language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - my
before_install: gem update --system
before_script:
  - "mysql -e 'create database thinking_sphinx;' > /dev/null"
  - "psql -c 'create database thinking_sphinx;' -U postgres >/dev/null"
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_0.gemfile